// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mufayphlmoqmgfadoimg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11ZmF5cGhsbW9xbWdmYWRvaW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTQyMjAsImV4cCI6MjA2OTY5MDIyMH0.HmcACmT8f5u-0vaH4xEMza0x0ShcmXw9NNGtIGKnc6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});